### ISSUE TITLE
zkraslit chyboce hlaseni

### ISSUE THREAD

**Issue by kn0t3k** [martinkntk/IIS#8]
a pridavani hudebniku, skladeb atd...

**Comment by kohuthonza** [comment]
ok ok :dancers:

**Comment by kohuthonza** [comment]
hlaska po pridani uzivatel hotova, je to dobra ***** :sleeping:

**Comment by kohuthonza** [comment]
hlaska po pridani skladby hotova :space_invader:

**Comment by kohuthonza** [comment]
hlaska po pridani hudebnika hotova :hamster:

**Comment by kohuthonza** [comment]
hlaska po odhlaseni hotova :bear:

**Comment by kn0t3k** [comment]
pridat hlasku po spatnem heslu

**Comment by kohuthonza** [comment]
hlášky "Zadejte login", "Zadejte heslo" a "Špatné heslo, nebo login" dodělány :turtle:

**Comment by kohuthonza** [comment]
hláška "Špatná délka rodného čísla" přidána :lollipop:

**Comment by kohuthonza** [comment]
hlášky "Uživatel s tímto loginem již existuje" a "Hudebník s tímto rodným číslem už existuje" přidány :key:  Uzavřeme, nebo je ještě něco třeba (kolem hlášek)?
